## Creating an ndarray

In [2]:
import numpy as np
narray = np.array([3,33,333])   #Creating a rank 1 array
print(type(narray))    #printing the type of array that narray is

<class 'numpy.ndarray'>


In [3]:
#Checking the shape of the object that was just created - it should have just one dimension
narray.shape

(3,)

In [4]:
#accessing elements of the array
print(narray[0],narray[1],narray[2])

3 33 333


## How to create a rank 2 numpy array

In [12]:
narray2 = np.array([[3,33,333],[22,222,2222]])
print(narray2)
print("The shape is",narray2.shape)
print("Accessing the elements of the array at positions: [0,0], [0,1], [1,2]", narray2[0,0],narray2[0,1],narray2[1,2])

[[   3   33  333]
 [  22  222 2222]]
The shape is (2, 3)
Accessing the elements of the array at positions: [0,0], [0,1], [1,2] 3 33 2222


## There are many ways to create a numpy array
Creating different size arrays with different prefilled values

In [14]:
#creating a 2X2 array with zeros
z = np.zeros((2,2)) 
print(z)

[[0. 0.]
 [0. 0.]]


In [17]:
#Creating a matrix with all elements of the matrix having the same value
ex1 = np.full((2,2),9)
print(ex1)

[[9 9]
 [9 9]]


In [18]:
#Creating a matrix with diagonal elements as 1 and the others as zero
ex2 = np.eye(2,2)
print(ex2)

[[1. 0.]
 [0. 1.]]


In [24]:
#Create an array of ones
ex3 = np.ones((1,2))
print(ex3)

[[1. 1.]]


In [26]:
#Creating a random array
ex4 = np.random.random((2,2))
print(ex4)

[[0.09312241 0.83104398]
 [0.94041106 0.84318315]]


## Creating an array of rank 2 with dimensions 3X4


In [28]:
arr = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(arr)
arr.shape

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


(3, 4)

In [33]:
arr_slice = np.array(arr[:2,1:3])
print(arr_slice)

[[12 13]
 [22 23]]


In [34]:
print("Before: ",arr[0,1])
arr[0,0] = 1000
print("After: ",arr[0,1])

Before:  12
After:  12


In [35]:
row_rank1 = arr[1, :]
row_rank1.shape

(4,)

In [37]:
row_rank2 = arr[1:2,:]
row_rank2.shape
print(row_rank2)

[[21 22 23 24]]


In [38]:
new_array = np.array([[11,12],[21,22],[31,32]])
print(new_array)

[[11 12]
 [21 22]
 [31 32]]


In [40]:
filter = (new_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [43]:
print(new_array[filter])

[21 22 31 32]


In [45]:
new_array[(new_array>20)&(new_array<30)]

array([21, 22])

In [46]:
new_array[new_array %2 ==0]

array([12, 22, 32])

In [49]:
new_array[new_array%2==0]+=100
print(new_array)

[[ 11 312]
 [ 21 322]
 [ 31 332]]


In [51]:
rand_arr = 10*np.random.randn(2,5)
print(rand_arr)

[[ -6.90283179 -11.59592512  22.14951203  18.23534053 -12.43074039]
 [ -2.07130924   1.43252628   4.72232355  -4.28136449   5.07630318]]


In [53]:
print(rand_arr.mean())

1.4333834532211855


In [54]:
print(rand_arr.sum())

14.333834532211856


In [56]:
print(rand_arr.mean(axis=0))

[-4.48707052 -5.08169942 13.43591779  6.97698802 -3.67721861]


In [58]:
print(rand_arr.mean(axis=1))

[1.89107105 0.97569586]


In [59]:
print(np.median(rand_arr,axis = 1))

[-6.90283179  1.43252628]


In [61]:
unsorted = np.random.randn(10)
print(unsorted)

[-0.62524197  0.25551482  0.52792641  0.29081131  0.20929656  1.35829664
 -0.87639359 -1.57820209 -0.91605798 -0.86452651]


In [64]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.57820209 -0.91605798 -0.87639359 -0.86452651 -0.62524197  0.20929656
  0.25551482  0.29081131  0.52792641  1.35829664]

[-0.62524197  0.25551482  0.52792641  0.29081131  0.20929656  1.35829664
 -0.87639359 -1.57820209 -0.91605798 -0.86452651]


In [65]:
unsorted.sort()
print(unsorted)


[-1.57820209 -0.91605798 -0.87639359 -0.86452651 -0.62524197  0.20929656
  0.25551482  0.29081131  0.52792641  1.35829664]


In [69]:
uni = np.array([1,2,2,2,1,4,5,6])
print(np.unique(uni))

[1 2 4 5 6]


In [71]:
s1 = np.array(["chair","table","shelf"])
s2 = np.array(["lamp","bulb","chair"])
print(s1,s2)

['chair' 'table' 'shelf'] ['lamp' 'bulb' 'chair']


In [73]:
print(np.intersect1d(s1,s2))

['chair']


In [74]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'lamp' 'shelf' 'table']


In [76]:
print(np.setdiff1d(s2,s1))

['bulb' 'lamp']


In [77]:
print(np.in1d(s1,s2))

[ True False False]


# Broadcasting


In [80]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [82]:
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [84]:
y = start+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]
